# Generated by Django 4.2 on 2023-05-01 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('estreno', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('video', models.IntegerField(blank=True, default=1, null=True)),
                ('caratula', models.ImageField(blank=True, null=True, upload_to='myimg')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('favoritos', models.ManyToManyField(related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('meGusta', models.ManyToManyField(related_name='Me_Gusta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
